# Generated by Django 3.0.8 on 2020-08-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anunciante',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='anunciante',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
